# Generated by Django 5.0.3 on 2024-03-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dateofcredits', models.DateTimeField(auto_now_add=True)),
                ('lastcredits', models.IntegerField()),
                ('lastpayment', models.IntegerField()),
                ('dateofpayment', models.DateTimeField(auto_now_add=True)),
                ('totalbalance', models.IntegerField()),
            ],
        ),
    ]
