# Generated by Django 5.0.3 on 2024-04-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_fname', models.CharField(max_length=100)),
                ('ct_lname', models.CharField(max_length=100)),
                ('ct_address', models.CharField(max_length=100, null=True)),
                ('ct_contact', models.IntegerField(max_length=11, null=True)),
                ('ct_birthday', models.DateField(max_length=20, null=True)),
            ],
        ),
    ]
