# Generated by Django 5.0.3 on 2024-04-21 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_date', models.DateField(max_length=20)),
                ('od_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_name', models.CharField(max_length=50)),
                ('pd_type', models.CharField(max_length=20)),
                ('pd_price', models.IntegerField(max_length=20)),
                ('pd_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Useracc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='ct_orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stickerou.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='od_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stickerou.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='od_useracc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stickerou.useracc'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ct_useracc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stickerou.useracc'),
        ),
    ]
