# Generated by Django 5.0.3 on 2024-05-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerou', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracc',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
