# Generated by Django 5.0.4 on 2024-05-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_ordering', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
