# Generated by Django 5.0.4 on 2024-05-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_ordering', '0008_category_alter_products_image_alter_products_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categ',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
