# Generated by Django 5.0.4 on 2024-05-04 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meat_ordering', '0011_category_remove_products_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
    ]
