# Generated by Django 5.0.4 on 2024-05-06 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meat_ordering', '0017_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
