# Generated by Django 5.0.3 on 2024-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0002_remove_useracc_user_email_useracc_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracc',
            name='user_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
