# Generated by Django 5.0.3 on 2024-05-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0007_remove_units_unit_rentalschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalschedule',
            name='rs_payment',
            field=models.IntegerField(null=True),
        ),
    ]
