# Generated by Django 5.0.3 on 2024-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0010_units_unit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ct_profile',
            field=models.ImageField(default='', upload_to='picture/images'),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit_image',
            field=models.ImageField(default='', upload_to='picture/images'),
        ),
    ]
