# Generated by Django 5.0.3 on 2024-05-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0011_alter_customer_ct_profile_alter_units_unit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ct_profile',
            field=models.ImageField(upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit_image',
            field=models.ImageField(upload_to='picture/'),
        ),
    ]
