# Generated by Django 5.0.3 on 2024-05-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0013_rentalschedule_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='unit_info',
            field=models.CharField(max_length=300),
        ),
    ]
