# Generated by Django 5.0.3 on 2024-05-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0014_alter_units_unit_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalschedule',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='rentalschedule',
            name='unit_color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
