# Generated by Django 5.0.3 on 2024-05-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0015_remove_rentalschedule_unit_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalschedule',
            name='unit_color',
        ),
    ]
