# Generated by Django 5.0.3 on 2024-05-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0017_rentalschedule_unit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalschedule',
            name='unit_id',
        ),
    ]
