# Generated by Django 5.0.3 on 2024-05-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0020_rental_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ct_userAcc',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='UserAcc',
        ),
    ]
