# Generated by Django 5.0.3 on 2024-05-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0021_remove_customer_ct_useracc_customer_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='ct_password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='ct_username',
        ),
    ]
