# Generated by Django 5.0.3 on 2024-05-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0022_rename_password_customer_ct_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ct_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ct_username',
            new_name='username',
        ),
    ]
