# Generated by Django 5.0.3 on 2024-05-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0024_rentalschedule_rs_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental_plans',
            name='plan_units',
        ),
    ]
