# Generated by Django 5.0.3 on 2024-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0025_remove_rental_plans_plan_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='unit_condition',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
