# Generated by Django 5.0.3 on 2024-05-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0027_customer_myadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ct_contact',
            field=models.IntegerField(null=True),
        ),
    ]
