# Generated by Django 5.0.3 on 2024-05-19 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0031_units_conditions_remove_units_unit_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalschedule',
            name='rs_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bajaj_system.rental_plans'),
        ),
    ]
