# Generated by Django 5.0.3 on 2024-05-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0032_remove_units_unit_condition_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='rentalrecord',
            name='rr_rentalSchedule',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
