# Generated by Django 5.0.3 on 2024-04-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_fname', models.CharField(max_length=100)),
                ('ct_mname', models.CharField(max_length=100)),
                ('ct_lname', models.CharField(max_length=100)),
                ('ct_birthday', models.DateField(max_length=100, null=True)),
                ('ct_address', models.CharField(max_length=100, null=True)),
                ('ct_contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RentalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_timeStart', models.TimeField(max_length=100, null=True)),
                ('rs_timeEnd', models.TimeField(max_length=100, null=True)),
                ('rs_date', models.DateField(max_length=100, null=True)),
                ('rs_type', models.CharField(max_length=100)),
                ('rs_payment', models.IntegerField()),
                ('rs_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bajaj_system.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_color', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=100, null=True)),
                ('unit_info', models.CharField(max_length=100)),
                ('unit_rentalSchedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bajaj_system.rentalschedule')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rr_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bajaj_system.customer')),
                ('rr_rentalSchedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bajaj_system.rentalschedule')),
                ('rr_units', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bajaj_system.units')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='ct_userAcc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bajaj_system.useracc'),
        ),
    ]
