# Generated by Django 5.0.3 on 2024-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0003_alter_useracc_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracc',
            name='user_confirmPass',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
