# Generated by Django 5.0.3 on 2024-04-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0004_useracc_user_confirmpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ct_userAcc',
        ),
        migrations.AddField(
            model_name='useracc',
            name='user_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bajaj_system.customer'),
        ),
    ]
