# Generated by Django 5.0.3 on 2024-04-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0006_remove_useracc_user_customer_customer_ct_useracc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='unit_rentalSchedule',
        ),
        migrations.AddField(
            model_name='rentalschedule',
            name='rs_units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bajaj_system.units'),
        ),
    ]
