# Generated by Django 5.0.3 on 2024-05-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0008_alter_rentalschedule_rs_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ct_profile',
            field=models.ImageField(default='', upload_to='static/picture'),
        ),
    ]
