# Generated by Django 5.0.3 on 2024-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0009_customer_ct_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='unit_image',
            field=models.ImageField(default='', upload_to='static/picture'),
        ),
    ]
