# Generated by Django 5.0.3 on 2024-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0012_alter_customer_ct_profile_alter_units_unit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalschedule',
            name='unit_id',
            field=models.IntegerField(null=True),
        ),
    ]
