# Generated by Django 5.0.3 on 2024-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0018_remove_rentalschedule_unit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrecord',
            name='present_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
