# Generated by Django 5.0.3 on 2024-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0026_units_unit_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='myadmin',
            field=models.BooleanField(default=False),
        ),
    ]
