# Generated by Django 5.0.3 on 2024-05-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0034_remove_units_unit_condition_rentalrecord_rr_plan'),
    ]

    operations = [
    ]
