# Generated by Django 5.0.3 on 2024-05-20 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajaj_system', '0035_remove_units_unit_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrecord',
            name='rr_rentalSchedule',
        ),
        migrations.RemoveField(
            model_name='rentalschedule',
            name='rs_timeEnd',
        ),
        migrations.AddField(
            model_name='customer',
            name='ct_units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bajaj_system.units'),
        ),
    ]
