# Generated by Django 5.0.3 on 2024-04-23 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greates_foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='foods',
            name='Town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greates_foods.town'),
        ),
    ]
